import profilesData from "@/data/profiles.json";
import type { DashboardBundle, FullAssessment, InvestmentPlan, ProfileSummary, RiskProfilePayload, RiskProfileResult } from "@/lib/types";

const DISCLAIMER = "Educational prototype only. SetuScore is not an official bureau score, and scenarios are not regulated financial advice or promised returns.";
type RawProfile = typeof profilesData[number];
const featureLabels:Record<string,string>={utility_on_time_ratio:"Utility payment punctuality",recharge_regularity:"Recharge regularity",transaction_stability:"Transaction stability",cashflow_volatility:"Cash-flow volatility",savings_rate:"Savings rate",failed_payment_ratio:"Failed payment ratio"};
const positive = new Set(["utility_on_time_ratio","recharge_regularity","transaction_stability","savings_rate","savings_streak_months","consent_completeness","digital_tenure_months"]);
const weights:Record<string,number>={recharge_regularity:58,recharge_amount_volatility:-32,utility_on_time_ratio:75,utility_avg_days_late:-2.8,commerce_frequency:1.1,commerce_refund_ratio:-55,transaction_stability:66,cashflow_volatility:-62,savings_rate:92,savings_streak_months:1.3,digital_tenure_months:.35,failed_payment_ratio:-110,consent_completeness:38};
function raw(id:string){return (profilesData as RawProfile[]).find(p=>p.profile_id===id)??profilesData[0];}
function scoreValue(features:Record<string,number>){let total=475;for(const [k,v] of Object.entries(features)) total+=(weights[k]??0)*v;return Math.max(300,Math.min(900,Math.round(total)));}
function risk(score:number){return score>=700?"Low":score>=520?"Medium":"High" as const;}
function summary(p:RawProfile):ProfileSummary{const score=scoreValue(p.features);return{profile_id:p.profile_id,name:p.name,role:p.role,city:p.city,monthly_income:p.monthly_income,monthly_expenses:p.monthly_expenses,monthly_surplus:Math.max(0,p.monthly_income-p.monthly_expenses),emergency_fund_months:p.emergency_fund_months,income_stability:p.income_stability,is_demo:true,consent_sources:p.consent.sources,score,risk_bucket:risk(score),confidence:Math.min(94,Math.round(68+p.features.consent_completeness*22))};}
export function demoProfiles(){return (profilesData as RawProfile[]).map(summary).sort((a,b)=>a.name.localeCompare(b.name));}
function projection(monthly:number,years:number,rates:[number,number,number]){return Array.from({length:years*12+1},(_,month)=>{const fv=(annual:number)=>{if(!month)return 0;const r=annual/12;return monthly*(((1+r)**month-1)/r)*(1+r)};return{month,contributed:month*monthly,conservative:fv(rates[0]),expected:fv(rates[1]),optimistic:fv(rates[2])}})}
export function assessRisk(r:RiskProfilePayload):RiskProfileResult{const surplus=Math.max(0,r.monthly_income-r.monthly_expenses);const ratio=surplus/Math.max(r.monthly_income,1);let appetite={1:18,2:38,3:58}[r.loss_reaction]+r.horizon_years*6+r.investment_experience*9;let capacity=Math.min(35,r.emergency_fund_months*7)+Math.min(30,ratio*100)+r.income_stability*6;appetite=Math.min(100,Math.round(appetite));capacity=Math.min(100,Math.round(capacity));const guardrails:string[]=[];let profile:InvestmentPlan=Math.min(appetite,capacity+10)<42?"Conservative":Math.min(appetite,capacity+10)<72?"Balanced":"Growth";if(r.emergency_fund_months<1||r.liquidity_need_months<=6){profile="Conservative";guardrails.push("Build accessible reserves before increasing market exposure.")}if(ratio<.1&&profile==="Growth"){profile="Balanced";guardrails.push("Keep contributions flexible while monthly surplus remains limited.")}return{appetite_score:appetite,capacity_score:capacity,profile,guardrails,explanation:[`Risk appetite: ${appetite}/100.`,`Financial capacity: ${capacity}/100.`,`The ${profile.toLowerCase()} result applies the more cautious signal and liquidity guardrails.`],disclaimer:DISCLAIMER}}
function allocation(plan:InvestmentPlan){return plan==="Conservative"?[["Stability-oriented",55],["Diversified growth",20],["Liquidity reserve",25]]:plan==="Growth"?[["Stability-oriented",20],["Diversified growth",65],["Liquidity reserve",15]]:[["Stability-oriented",40],["Diversified growth",40],["Liquidity reserve",20]];}
export function demoBundle(id:string,monthly=2000,years=3):DashboardBundle{const p=raw(id);const profile=summary(p);const score=profile.score!;const ranked=Object.entries(p.features).map(([feature,value])=>({feature,value,impact:(weights[feature]??0)*value})).sort((a,b)=>Math.abs(b.impact)-Math.abs(a.impact)).slice(0,3);const plan:InvestmentPlan=profile.emergency_fund_months<1?"Conservative":"Balanced";const rates:Record<InvestmentPlan,[number,number,number]>={Conservative:[.045,.06,.075],Balanced:[.05,.08,.11],Growth:[.055,.10,.14]};const series=projection(monthly,years,rates[plan]);return{profile,features:p.features,consent:p.consent,score:{profile_id:id,probability:(score-300)/600,score,risk_bucket:risk(score),confidence:profile.confidence!,top_drivers:ranked.map(x=>({feature:x.feature,label:featureLabels[x.feature]??x.feature.replaceAll("_"," "),group:"Alternative signal",direction:(positive.has(x.feature)?x.value>=.5:x.value<.4)?"positive":"negative",impact_points:Math.max(-18,Math.min(18,Math.round(x.impact/5))),value:x.value,baseline:.5,explanation:`${featureLabels[x.feature]??x.feature.replaceAll("_"," ")} is ${positive.has(x.feature)?"supporting":"influencing"} this transparent demo result.`})),improvement_actions:[{feature:"utility_on_time_ratio",label:"Utility payment punctuality",current_value:p.features.utility_on_time_ratio,target_value:Math.min(1,p.features.utility_on_time_ratio+.08),current_score:score,projected_score:Math.min(900,score+14),score_gain:14,action:"Pay utility bills before the due date for three consecutive months."},{feature:"savings_rate",label:"Savings consistency",current_value:p.features.savings_rate,target_value:Math.min(.6,p.features.savings_rate+.04),current_score:score,projected_score:Math.min(900,score+9),score_gain:9,action:"Maintain a small automatic savings transfer every month."}],method:"Deterministic TypeScript fallback used only when the FastAPI ML service is unavailable.",disclaimer:DISCLAIMER},recommendation:{plan,monthly_amount:monthly,years,allocation:allocation(plan).map(([category,percentage])=>({category:String(category),percentage:Number(percentage),rationale:"Broad educational category selected using liquidity and capacity guardrails."})),guardrails:profile.emergency_fund_months<1?["Build an emergency reserve first."]:[],plain_language_summary:`A ${plan.toLowerCase()} educational allocation for ₹${monthly.toLocaleString("en-IN")} per month.`,disclaimer:DISCLAIMER},simulation:{plan,monthly_amount:monthly,years,assumptions:{method:"Deterministic educational scenarios"},final_values:{contributed:series.at(-1)?.contributed??0,conservative:series.at(-1)?.conservative??0,expected:series.at(-1)?.expected??0,optimistic:series.at(-1)?.optimistic??0},series,disclaimer:DISCLAIMER},disclaimer:DISCLAIMER}}
export function demoAssessment(profileId:string,monthly:number,years:number,riskPayload:RiskProfilePayload):FullAssessment{const bundle=demoBundle(profileId,monthly,years);const rr=assessRisk(riskPayload);const alloc=allocation(rr.profile).map(([category,percentage])=>({category:String(category),percentage:Number(percentage),rationale:"Broad educational category selected using liquidity and capacity guardrails."}));const rates:Record<InvestmentPlan,[number,number,number]>={Conservative:[.045,.06,.075],Balanced:[.05,.08,.11],Growth:[.055,.10,.14]};const series=projection(monthly,years,rates[rr.profile]);return{profile:bundle.profile,score:bundle.score,risk_profile:rr,recommendation:{plan:rr.profile,monthly_amount:monthly,years,allocation:alloc,guardrails:rr.guardrails,plain_language_summary:`A ${rr.profile.toLowerCase()} educational allocation for ₹${monthly.toLocaleString("en-IN")} per month.`,disclaimer:DISCLAIMER},simulation:{plan:rr.profile,monthly_amount:monthly,years,assumptions:{method:"Deterministic educational scenarios"},final_values:{contributed:series.at(-1)?.contributed??0,conservative:series.at(-1)?.conservative??0,expected:series.at(-1)?.expected??0,optimistic:series.at(-1)?.optimistic??0},series,disclaimer:DISCLAIMER},disclaimer:DISCLAIMER}}
